<?php
/**
 * @file
 * Provides Feeds integration for Field Collection.
 */

/**
 * Implements hook_autoload_info().
 */
function field_collection_feeds_autoload_info() {
  return array(
    'FeedsFieldCollectionProcessor' => 'plugins/FeedsFieldCollectionProcessor.inc',
  );
}

/**
 * Implements hook_feeds_plugins().
 */
function field_collection_feeds_feeds_plugins() {
  $info = array(
    'FeedsFieldCollectionProcessor' => array(
      'name' => 'Field collection processor',
      'module' => 'field_collection_feeds',
      'description' => 'Create and update field collection items.',
      'help' => 'Create and update field collection items from parsed content.',
      'handler' => array(
        'parent' => 'FeedsProcessor',
        'class' => 'FeedsFieldCollectionProcessor',
        'file' => 'FeedsFieldCollectionProcessor.inc',
        'path' => backdrop_get_path('module', 'field_collection_feeds'),
      ),
    ),
  );
  return $info;
}
